### ISSUE TITLE
Having fun with Symfony and a Raspberry Pi

### ISSUE THREAD

**Issue by jcornide** [symfony-cat/cfp-2017#10]
## Jose Cornide

- [LinkedIn](https://es.linkedin.com/in/jcornide)

---

Do you know about the Raspberry Pi? Most likely you do. Do you have one? Probably you bought it as a media player, a torrent downloader, a NAS controller... But, do you know you can interact with its GPIO with Symfony?

In this talk I'll show you how to create very simple applications to interact with the Raspberry Pi like a temperature reader or a camera switch and bring Symfony to the actual physical world.

**Comment by vguardiola** [comment]
Muy a pesar nuestro hemos decidido suspender la edición de Symfony Cat 2017. Disculpar las molestias.
We have decided to suspend the edition of Symfony Cat 2017. Sorry for the inconvenience.
