### ISSUE TITLE
How to improve performance of your Symfony application

### ISSUE THREAD

**Issue by dbrumann** [symfony-cat/cfp-2017#12]
## Denis Brumann

- [SensioLabs Connect](https://connect.sensiolabs.com/profile/dbrumann)
- [twitter](https://twitter.com/dbrumann)
- [GitHub](https://github.com/dbrumann)

My credentials are that I made a contribution to Symfony that impacted performance with PHP 7 symfony/symfony#20735 (admittedly the groundwork for finding the issue was done by others as outlined in the PR). I have prior experience giving talks at company internal tech talks at my previous company and at the PHP usergroup Berlin.

---

Over the last few years I was working mostly with legacy PHP-applications and one concern that either pops up way too early or way too late in a project's lifecycle is performance. I have seen developers come up with elaborately crafted, but hard to read (and maintain) code for the sake of performance, but not back up their claims with actual data. I have argued with people about micro-optimizations saving a few cpu-ticks when in the meantime huge amounts of data were loaded into memory making the site bog-slow.

In my talk I want to lay out how to effectively anticipate, identify and mitigate performance issues in a common Symfony application as well as show some configurations and components that will help you increase performance that come out of box.

I want to focus on the following points in more details:

 - Why are micro-optimizations bad and when are they a viable option?
 - How to investigate performance problems using Xdebug profiling, Blackfire and other tools?
 - Boosting performance of your Symfony-application (configuration, caching, utilizing HTTP cache)
 - Monitoring performance and revisiting previous solutions

This is an advanced topic and I plan to make it more graphic and less intimidating by working on examples I have encountered in my work such as:

 - Working on a Symfony PR with performance implications in different PHP-versions
 - Loading a complete translation catalog & passing it to the frontend and the performance problems it caused and how we started migrating over to Symfony\Translator.
 - A custom Filesystem-Cache that was slowing the application down (and eat up lots of disk space) and how it was replaced with Doctrine's Cache-component
 - Loading heavy services from the container, how it "shadowed" other performance problems and how we used proxy-loading services from the container to reveal (and tackle) the underlying issues

**Comment by vguardiola** [comment]
Muy a pesar nuestro hemos decidido suspender la edición de Symfony Cat 2017. Disculpar las molestias.
We have decided to suspend the edition of Symfony Cat 2017. Sorry for the inconvenience.
