### ISSUE TITLE
Taking out the batteries - How to build your own framework

### ISSUE THREAD

**Issue by dbrumann** [symfony-cat/cfp-2017#13]
## Denis Brumann

- [SensioLabs Connect](https://connect.sensiolabs.com/profile/dbrumann)
- [twitter](https://twitter.com/dbrumann)
- [GitHub](https://github.com/dbrumann)

---

There is a common theme in frameworks and applications that they come _with batteries included_. You don’t have to care about wiring up the bare necessities and endlessly configure and tweak things, just go build your thing. This convenience usually comes at a cost: You are less flexible when you want to do things differently. Symfony has a MicroKernelTrait, but would you really choose Symfony for a small webservice that requires a micro framework? Probably you’d rather go with Zend Expressive, Silex or Slim. In my talk I want to show how to build your own micro framework and a basic web application with Symfony components.

With this talk I hope to give you a better understanding of the inner workings of a web application in general and a Symfony application in particular.  My talk revolves around a small example project using some core components such as the http-kernel, routing and the service container. The goal of this talk is not to create a ready to use-framework, but to give you a better understanding for some of the inner workings of your Symfony application. At the same time I want to show where the benefits, conveniences, but also downsides of a micro/macro framework lie.

This talk draws inspiration from and builds upon the article series [Create your own PHP framework](https://symfony.com/doc/master/create_framework/index.html) from the Symfony documentation.

**Comment by vguardiola** [comment]
Muy a pesar nuestro hemos decidido suspender la edición de Symfony Cat 2017. Disculpar las molestias.
We have decided to suspend the edition of Symfony Cat 2017. Sorry for the inconvenience.
