### ISSUE TITLE
A Beginner's Guide to Testing

### ISSUE THREAD

**Issue by dbrumann** [symfony-cat/cfp-2017#14]
## Denis Brumann

- [SensioLabs Connect](https://connect.sensiolabs.com/profile/dbrumann)
- [twitter](https://twitter.com/dbrumann)
- [GitHub](https://github.com/dbrumann)

---

Getting into writing automated tests can be a daunting task even for seasoned developers. There is all these buzzwords flying around, you might work on an existing project were every time you start writing a test it feels awkward, complicated and somewhat pointless or there is just so much code you don't know where to start.

In this talk I want to help you overcome these obstacles and give you quick introduction into the basics of testing. From writing a first test, mocking dependencies, to practical advice on how to easily test your existing Symfony application. Along the way I want to provide you ideas for fun exercises that help you boost your motivation and confidence in writing tests.

This talk is aimed at beginners who have little to no experience writing tests. It will cover basics of Unit, Functional and Acceptance Testing a Symfony application with PHPUnit (the latter with Symfony's WebTestCase).

**Comment by vguardiola** [comment]
Muy a pesar nuestro hemos decidido suspender la edición de Symnfony Cat 2017. Disculpar las molestias.
We have decided to suspend the edition of Symnfony Cat 2017. Sorry for the inconvenience.
