### ISSUE TITLE
PSRs, PSRs everywhere

### ISSUE THREAD

**Issue by hannesvdvreken** [symfony-cat/cfp-2017#15]
## Hannes Van De Vreken

- [Github](https://github.com/hannesvdvreken)
- [Twitter](https://twitter.com/hannesvdvreken)
- [Personal](https://hannesvdvreken.com)
- [Speakerdeck](https://speakerdeck.com/hannesvdvreken)
- [joind.in](https://joind.in/user/hannesvdvreken/talks)

---

### Abstract:

Symfony does a great job of keeping up with adopting PSRs. But what are they? Which PSRs can we use? And why should we use them? A full overview will be done and explained how to use them in Symfony.

### About this talk:

In this talks I will be explaining different PSRs, their reason for existance, and how to use them in Symfony.

---

Previous conferences where I've talked:
- [Laracon EU, 2014](http://laracon.eu/2014)
- [Laracon EU, 2015](http://laracon.eu/2015) ([video](https://www.youtube.com/watch?v=lreUaGnOOYs))
- [Fosdem, 2016](https://fosdem.org/2016/schedule/event/psr7httpinthewild/) ([video](http://mirror.onet.pl/pub/mirrors/video.fosdem.org/2016/h1308/psr-7-http-messages-in-the-wild.mp4))
- [PHP UK conference, 2016](phpconference.co.uk/schedule/#breakout-hannes-van-de-vreken) ([video](https://www.youtube.com/watch?v=gOVALgpqHzM))
- [PHPDay, 2016](http://2016.phpday.it) ([video](https://vimeo.com/channels/phpday/177154169))
- [PHPKonf, Istanbul, 2016](http://phpkonf.org)
- [PHP Tour (France), 2016](http://event.afup.org) ([video](https://www.youtube.com/watch?v=OtBxqoCJl6c))
- [Dutch PHP Conference, 2016](http://www.phpconference.nl)
- [Laracon EU, 2016](http://laracon.eu/2016/) ([video](https://www.youtube.com/watch?v=WMT8txJHdKI))
- [PHPCon Poland, 2016](http://www.phpcon.pl/2016/en/)
- [Webcamp Zagreb, 2016](https://2016.webcampzg.org/) ([video](https://youtu.be/qK8d5_saP7Y))
- [PHP Benelux, 2017](https://conference.phpbenelux.eu/2017/)
- [PHP UK conference, 2017](phpconference.co.uk/schedule/)
- [LaraveLive India, 2017](http://www.laravellive.in/)

Next speaking engagements:
- [PHP Unicorn conference, 2017](http://phpunicorn.com/)
- [DevTalks, Romania, 2017](http://www.devtalks.ro/cluj/)
- [PHP Tour Nantes, France, 2017](http://event.afup.org/phptournantes2017/programme/)
- [WebSummerCamp, 2017](http://2017.websummercamp.com)

**Comment by vguardiola** [comment]
Muy a pesar nuestro hemos decidido suspender la edición de Symfony Cat 2017. Disculpar las molestias.
We have decided to suspend the edition of Symfony Cat 2017. Sorry for the inconvenience.
