### ISSUE TITLE
From monolith to microservices (a story about Symfony bundles)

### ISSUE THREAD

**Issue by patxi1980** [symfony-cat/cfp-2017#16]
## Aitor Suso

- [GitHub](https://github.com/patxi1980)
- [Twitter](https://twitter.com/patxi1980)
- [Linkedin](https://www.linkedin.com/in/patxi1980)
- [SensioLabs](https://connect.sensiolabs.com/profile/patxi1980)

---

Big companies are using or currently migrating to a microservices architecture, because of the big advantages. But when you work in a company with high technical debt, lot of legacy code, or only one big monolith; starting to migrate into APIs could be a pain in the ass.

That's why instead of going crazy and trying to beginning to create lots of APIs, maybe it is time to use Symfony and its bundles in our advantage. In order to use them as an intermediate step in order to centralize and separate logic into small services. 

The talk will be address to smalls teams of smalls companies, that want to do the things right (separate concerns, smalls services, decoupled code, ...) but they don't have the expertise, skills or enough people to begin to create APIs, deploy serves, solves problems of replication data and all the needs to migrate into a microservices architecture.

Also the talk will be oriented as how create a service in a new project, convert it to a bundle in order to use in your current symfony project, and finally convert into an API. With this you will be able to deliver things fast to your business, but without losing the possibility to extend and improve in the future.

**Comment by patxi1980** [comment]
This talk will be very similar to the one i will do in the #desymfony http://desymfony.com/ponencia/del-monolito-a-los-microservicios-sin-morir-en-el-intento

I told because, repeated talks would be deleted.

When i create the issue, my talk in the desymfony has not been accepted yet.

**Comment by vguardiola** [comment]
Muy a pesar nuestro hemos decidido suspender la edición de Symfony Cat 2017. Disculpar las molestias.
We have decided to suspend the edition of Symfony Cat 2017. Sorry for the inconvenience.

**Comment by abozhinov** [comment]
Hi @patxi1980,
Like you are writing about me 😁.
I have huge monolith on Symfony 3.3 with some legacy code with no tests. I looking for painless way to migrate from monolith to Microservices. The final goal is to have API bases platform with ReactJS for UI. The idea is to make things smoothly because I can stop all new features and refactoring the code for half year.
