### ISSUE TITLE
CFP deadline and submission form?

### ISSUE THREAD

**Issue by ondrejmirtes** [symfony-cat/cfp-2017#4]
Nowhere to be seen.

**Comment by mmoreram** [comment]
@ondrejmirtes Submission Form? Have you read the repository README?

About the deadline, the 30 April we will close the CFP, and people will be able to vote until 31 May. I will add a Milestone for that.

**Comment by ondrejmirtes** [comment]
I suppose that I should create an issue (there's the sentence "And you don't have to leave Github!") but it's really not specifically said in the README. Read it :)

Please paste here the sentence where you're telling speakers that the proposal should be added as an issue to this repository. I don't see it.

**Comment by ondrejmirtes** [comment]
Also, I think the deadline should be mentioned in the README as well, just creating a milestone date is too buried in GitHub.

**Comment by mmoreram** [comment]
yes XD doing that XD just a sec

**Comment by mmoreram** [comment]
@ondrejmirtes hmmm, you're totally right! :o

My apologies, I will update the README right now in order to make it much more clear for everyone.

Thank you for your feedback :1st_place_medal:

**Comment by ondrejmirtes** [comment]
I just think that basic stuff like this should be obvious. You're welcome :)

**Comment by mmoreram** [comment]
@ondrejmirtes Done!

https://github.com/symfony-cat/cfp-2017
