### ISSUE TITLE
PSR-7 HTTP messages in the wild

### ISSUE THREAD

**Issue by hannesvdvreken** [symfony-cat/cfp-2017#6]
## Hannes Van De Vreken

- [Github](https://github.com/hannesvdvreken)
- [Twitter](https://twitter.com/hannesvdvreken)
- [Personal](https://hannesvdvreken.com)
- [Speakerdeck](https://speakerdeck.com/hannesvdvreken)
- [joind.in](https://joind.in/user/hannesvdvreken/talks)

---

### Abstract

PSR-7 describes common interfaces for representing HTTP messages. HTTP messages are the foundation of web development. Web browsers and HTTP clients such as cURL create HTTP request messages that are sent to a web server, which provides an HTTP response message. Server-side code receives an HTTP request message, and returns an HTTP response message.

This talk will explain the interfaces defined by PSR-7, how they define the future of interoperability between frameworks and tools. After that there will be a showcase of several implementations and tools such as zend's diactoros package, Guzzle v6, php-http, RelayPHP and other packages that show the real power of shared interfaces for HTTP objects. A clear path to how we can start using these typed objects in our applications today will be shown.

### About this talk:

Slides:
https://speakerdeck.com/hannesvdvreken/modern-http-handling-with-php-dutch-php-conference

Demo code used during this talk:
https://github.com/hannesvdvreken/psr7-demo

Video of me doing this talk at PHP UK 2016:
https://youtu.be/gOVALgpqHzM

Performed it at these occasions:

- PHP Gent meetup (http://www.meetup.com/phpgent/events/223410703/)
- PHP Leuven meetup (http://www.meetup.com/PHP-Leuven-Web-Innovation-Group/events/224396488/)
- PHP West-Vlaanderen meetup (http://www.meetup.com/php-wvl/events/225865878/)
- PHP Limburg meetup (http://www.meetup.com/PHP-Limburg-BE/events/226651311/)
- FOSDEM, Brussels (https://fosdem.org/2016/schedule/event/psr7httpinthewild/)
- PHP UK conference, London (http://phpconference.co.uk/schedule/#breakout-hannes-van-de-vreken)
- BredaPHP meetup (http://www.meetup.com/BredaPHP/events/228459009/)
- Istanbul PHP (http://phpkonf.org/)
- Dutch PHP conference 2016 (http://www.phpconference.nl/schedule)
- PHPCon Polan 2016 (http://www.phpcon.pl/2016/pl/)

Feedback:

- https://joind.in/talk/f21b2
- https://joind.in/talk/6ef7d
- https://joind.in/talk/b34d2
- https://joind.in/talk/e833b
- https://joind.in/talk/87f8c
...

---
Notes to organisers:

Previous conferences where I've talked:
- [Laracon EU 2014](http://laracon.eu/2014)
- [Laracon EU 2015](http://laracon.eu/2015) ([video](https://www.youtube.com/watch?v=lreUaGnOOYs))
- [Fosdem 2016](https://fosdem.org/2016/schedule/event/psr7httpinthewild/) ([video](http://mirror.onet.pl/pub/mirrors/video.fosdem.org/2016/h1308/psr-7-http-messages-in-the-wild.mp4))
- [PHP UK conference 2016](phpconference.co.uk/schedule/#breakout-hannes-van-de-vreken) ([video](https://www.youtube.com/watch?v=gOVALgpqHzM))
- [PHPDay 2016](http://2016.phpday.it) ([video](https://vimeo.com/channels/phpday/177154169))
- [Istanbul PHP 2016](http://phpkonf.org)
- [PHP Tour 2016 (France)](http://event.afup.org) ([video](https://www.youtube.com/watch?v=OtBxqoCJl6c))
- [Dutch PHP Conference](http://www.phpconference.nl)
- [Laracon EU 2016](http://laracon.eu/2016/) ([video](https://www.youtube.com/watch?v=WMT8txJHdKI))
- [PHPCon Poland 2016](http://www.phpcon.pl/2016/en/)
- [Webcamp Zagreb 2016](https://2016.webcampzg.org/) ([video](https://youtu.be/qK8d5_saP7Y))

Next speaking engagements:
- [PHP Benelux](https://conference.phpbenelux.eu/2017/)
- [PHP UK conference 2017](phpconference.co.uk/schedule/)

**Comment by mmoreram** [comment]
Dear @hannesvdvreken.

Thanks for your talk submission.
Unfortunately we have to reject them all, not because they are not interesting, not at all, but because they do not comply all requirements.

* All submissions must be unique and the first time they are exposed at any conference.

This message applies to these submissions

* https://github.com/symfony-cat/cfp-2017/issues/6
* https://github.com/symfony-cat/cfp-2017/issues/7
* https://github.com/symfony-cat/cfp-2017/issues/8
* https://github.com/symfony-cat/cfp-2017/issues/9

I'm sorry, but we have to be strict on this requirement.
Anyway, we encourage you to think about another talk, related somehow to the Symfony environment.

Thanks.

**Comment by hannesvdvreken** [comment]
@mmoreram oh wow. 😌 My bad! Didn't read the full instructions (tldr). But I am OK with that. I'll spend some time creating a new one for you!

**Comment by mmoreram** [comment]
@hannesvdvreken That would be perfect :D

Thanks for understanding :)
